config/routes.rb
Rails.application.routes.draw do

  root 'pintures#home'

  get 'signup' => 'users#new', as: :sign_up
  post 'signup' => 'users#create', as: :users

  get 'user/show' => 'users#show', as: :user

  get 'signin' => 'sessions#new', as: :sign_in
  post 'signin' => 'sessions#create', as: :auth

  get 'signout' => 'sessions#delete', as: :sign_out

  get 'new_pinture' => 'pintures#new', as: :new_pinture
  post 'create_pinture' => 'pintures#create', as: :pintures

  get 'pinture' => 'pintures#show', as: :pinture_modal

end

app/models/pinture.rb
class Pinture < ActiveRecord::Base

  belongs_to :user
  mount_uploader :photo, PhotoUploader
  validates :photo, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :pintures
  validates :email, :username, :password, presence: true
  validates :email, uniqueness: true, length: { minimum: 4 }
  validates :username, uniqueness: true, length: { minimum: 3 }
  validates :password, length: { minimum: 5 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_flash_types :success

end

app/controllers/pintures_controller.rb
class PinturesController < ApplicationController

  before_action do
    @current_user = User.find_by(id: session[:current_user])
    @pintures = Pinture.all.order('created_at desc').page(params[:page])
  end

  def home
    @user = User.new
  end

  def new
    @pinture = Pinture.new
  end

  def create
    @pinture = Pinture.new params.require(:pinture).permit(:photo, :comment, :link, :user_id)
    @pinture.save
  end

  def show
    @pinture = Pinture.find_by(id: params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    email = params[:session][:email]
    password = params[:session][:password]

    user = User.find_by(email: email)

      if (user) && (user.authenticate password)
        session[:current_user] = user.id
        @current_user = user
      end
  end

  def delete
    session.delete :current_user
    redirect_to root_path, notice: 'Successfully logged out'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pintures_helper.rb
module PinturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterested</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="main">

  <% if notice %>
    <div class="alert alert-warning">
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger">
      <%= alert %>
    </div>
  <% end %>

  <% if success %>
    <div class="alert alert-success">
      <%= success %>
    </div>
  <% end %>

<div class="container">
  <%= yield %>
</div>


<div class="modal fade big-modal" id="pinture-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Welcome to Pinterested</h4>
      </div>
      <div class="modal-body">
        MODAL BODY
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

</body>
</html>

app/views/pintures/_main.html.erb
<div style="margin:10px" class="nav-btn" id="smaller-margin">
  <%= link_to "Log Out", sign_out_path, class: "btn btn-primary"  %>
</div>
<h1 class="main">Show You Are Pinterested</h1>

<div style="margin:20px;">
  <%= link_to "New Pinture", new_pinture_path, remote: true, class: "btn btn-primary"  %>
</div>

<%= paginate @pintures %>
<div class="pics">
    <div class="row">
      <% @pintures.each do |pinture| %>
        <div class="col-sm-12 col-md-3 icon">
          <%= link_to pinture_modal_path(id: pinture.id), remote: true do %>
            <%= image_tag pinture.photo.url(:pinture), class: 'img-rounded img-responsive' %>
            <p>Pinned by <%= pinture.user.username %> <%= time_ago_in_words pinture.created_at %> ago</p>
          <% end %>
        </div>
      <% end %>
    </div>
</div>

<%= paginate @pintures %>

app/views/pintures/_new_pinture.html.erb
<!-- form for new pin (or Interest)-->
<%= simple_form_for @pinture, remote: true do |f| %>
  <%= f.input :photo %>
  <%= f.input :link, placeholder: "Must begin with http://" %>
  <%= f.input :comment %>
  <%= f.input :user_id, as: :hidden, input_html: {value: @current_user.id} %>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/pintures/_pinture_content.html.erb
<div class="center-block">
  <%= image_tag @pinture.photo.url(:pinture), class: "img img-responsive" %>
  <a href="<%= @pinture.link %>" target="_blank"><%= @pinture.link %></a>
  <h4>
      <%= @pinture.comment %>
  </h4>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
</div>

app/views/pintures/create.js.erb
<% if @pinture.save %>
  $('#pinture-modal').modal("hide");
  $('.container').html("<%= j render partial: 'main' %>");
<% else %>
    $('#pinture-modal .modal-title').html("New Interest");
    $('#pinture-modal .modal-body').html("<%= j render partial: 'new_pinture' %>");
<% end %>

app/views/pintures/home.html.erb
<% if @current_user.nil? %>
  <div class="welcome">
      <h1>Are You Pinterested?</h1>

      <%= link_to "Sign Up Here", sign_up_path, remote: true, class: "btn btn-danger"  %>
       or <%= link_to "Sign In Here", sign_in_path, remote: true, class: "btn btn-danger" %>
  </div>
<% else %>
  <%= render partial: 'main' %>
<% end %>

app/views/pintures/new.js.erb
$('#pinture-modal .modal-body').html("<%= j render partial: 'new_pinture' %>");

$('#pinture-modal').modal("show");

app/views/pintures/show.js.erb
$(".modal-header").remove();
$('#pinture-modal .modal-body').html("<%= j render partial: 'pinture_content' %>");
$('#pinture-modal').modal("show");

app/views/users/_signup.js.erb
<h2>Sign Up</h2>
<%= simple_form_for @user, remote: true do |f| %>
  <%= f.input :email %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.input :password_confirmation, label: "Confirm password" %>
  <%= f.submit "Sign Up", class: "btn btn-primary" %>
<% end %>

app/views/users/create.js.erb
<% if @user.save %>
  <% session[:current_user] = @user.id %>
  window.location = "/";
<% else %>
  $('#pinture-modal .modal-body').html("<%= j render partial: 'signup' %>");
<% end %>

app/views/users/new.js.erb
$('#pinture-modal .modal-body').html("<%= j render partial: 'signup' %>");

$('#pinture-modal').modal("show");

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>